name:                lambda-reasoner
version:             0.1.0.0
github:              "wasabi315/lambda-reasoner"
license:             BSD-3-Clause
author:              "Satoshi Takimoto"
maintainer:          "takimoto.s.ab@m.titech.ac.jp"
copyright:           "2024 Satoshi Takimoto"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wasabi315/lambda-reasoner#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - ideas
  - containers

executables:
  lambda-reasoner-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-reasoner
    - ideas
    - containers

tests:
  lambda-reasoner-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-reasoner
